//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChuVanDiep_1811062670.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class baihat
    {
        public long mabaihat { get; set; }
        public string Tenbaihat { get; set; }
        public long Theloai { get; set; }
        public string casi { get; set; }
        public string tacgia { get; set; }
        public string hinhanh { get; set; }
        public Nullable<int> thich { get; set; }
        public string loibaihat { get; set; }
    
        public virtual TheLoai TheLoai1 { get; set; }
    }
}
